astrosmash.prg: astrosmash.asm
	acme astrosmash.asm

play: astrosmash.prg
	open astrosmash.prg

play-win: astrosmash.prg
	/cygdrive/c/Program\ Files\ \(x86\)/WinVICE-2.4-x86/x64.exe  ./astrosmash.prg
